### ISSUE TITLE
Add a spec for the username mappings

### ISSUE THREAD

**Issue by rpanderson** [philipstarkey/bitbucket-hg-exporter#2]
In the interactive CLI, there's the following prompt:

> Enter the path to a JSON file containing username mappings between BitBucket and GitHub

What's the spec for the JSON file?

**Comment by philipstarkey** [comment]
FYI, (unrelated to this issue) issues on GitHub don't auto close on a commit if you put the word "issue" between the number and the close keyword ("fixes" in this case). See a comment on: https://stackoverflow.com/a/6742691

**Comment by philipstarkey** [comment]
Also, this is what the documentation now says:

It should be a JSON file of the format:

```
{
    "bitbucket_username1a": "associated GitHub username 1",
    "bitbucket_username1b": "associated GitHub username 1",
    "bitbucket_username2": "associated GitHub username 2"
}
```
Note that you can have multiple BitBucket usernames pointing to the same GitHub username (useful if someone has multiple BitBucket accounts but only one relevant GitHub account).
