### ISSUE TITLE
ModuleNotFoundError: No module named 'OpenSSL'

### ISSUE THREAD

**Issue by scpeters** [philipstarkey/bitbucket-hg-exporter#21]
I'm using Ubuntu 18.04, and I just did `pip install bitbucket_hg_exporter` in a fresh python3.7 venv and it cannot import `OpenSSL.SSL`:

~~~
(bb_venv) $ bitbucket-hg-exporter 
Traceback (most recent call last):
  File "/data_fast/scpeters/ws/bb_venv/bin/bitbucket-hg-exporter", line 5, in <module>
    from bitbucket_hg_exporter.__main__ import main
  File "/data_fast/scpeters/ws/bb_venv/lib/python3.7/site-packages/bitbucket_hg_exporter/__main__.py", line 28, in <module>
    from OpenSSL.SSL import SysCallError
ModuleNotFoundError: No module named 'OpenSSL'
~~~

I'm guessing a dependency is missing from requirements.txt?

**Comment by philipstarkey** [comment]
You can try using pip to install pyOpenSSL but my experience with that in Linux has been less than ideal. You are better off using your system package manager to install it if available, or using Anaconda Python (which should ship with it). Let me know whether either of these suggestions fix the problem. If installing from pip works I might add it to the requirements list (I'll need to confirm it works on windows too though)

**Comment by scpeters** [comment]
gotcha; I'll try it with pip

it could be an additional part of the installation instructions if it doesn't work well in requirements.txt

**Comment by philipstarkey** [comment]
Oh.. looks like that import isn't even used...wow I'm an idiot.
I'll release a new version shortly that shouldn't need OpenSSL

**Comment by scpeters** [comment]
oh, no problem, thanks for the quick responses

**Comment by philipstarkey** [comment]
Version 0.5.7 should now be on PyPI (sometimes pip won't find the new version because it caches it...you can either wait it out, find the instructions for clearing the cache, or download the whl directly from PyPI and point pip at it).

Let me know if 0.5.7 solves the issue (I'll leave this open for now)

**Comment by scpeters** [comment]
if I have other questions about how code works that isn't really a bug report, (like is it possible to use the program for public bitbucket repositories without typing my password), should I create issues for that or communicate on some other channel? (or just leave you alone and figure it out myself)

**Comment by scpeters** [comment]
> Let me know if 0.5.7 solves the issue (I'll leave this open for now)

testing...

**Comment by scpeters** [comment]
looks good!

**Comment by philipstarkey** [comment]
Great, thanks for testing!
