### ISSUE TITLE
SyntaxError in __main__.py

### ISSUE THREAD

**Issue by levitsky** [philipstarkey/bitbucket-hg-exporter#24]
There is a syntax error here (missing comma): https://github.com/philipstarkey/bitbucket-hg-exporter/blob/c191d4a2dcf48333144ae47f89586758acd4c5dc/bitbucket_hg_exporter/__main__.py#L691

**Comment by levitsky** [comment]
Update: there were two more syntax errors in the file, PR #25 fixes them.

**Comment by philipstarkey** [comment]
Fixed in #28
