### ISSUE TITLE
How to get a Bitbucket access token?

### ISSUE THREAD

**Issue by levitsky** [philipstarkey/bitbucket-hg-exporter#26]
I am using Google to authenticate on Bitbucket. I was unable to find where to get/generate a token that I could provide to bitbucket-hg-exporter. It would be nice to have this information in the readme.

**Comment by philipstarkey** [comment]
I believe it may actually be called an app password (distinct from oauth2 tokens). Try following this and let me know if it doesn't work: https://stackoverflow.com/a/39926410

**Comment by levitsky** [comment]
Yes, that's it. Thank you!
