### ISSUE TITLE
github_URL_rewrite_file_path does not exist

### ISSUE THREAD

**Issue by rpanderson** [philipstarkey/bitbucket-hg-exporter#3]
Testing this with a few Bitbucket repositories (not yet on Github, no issue tracking or backup to Github pages required), I get the following error:

```python
Traceback (most recent call last):
  File "c:\users\rpanderson\appdata\local\continuum\anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\rpanderson\appdata\local\continuum\anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\rpanderson\appdata\local\continuum\anaconda3\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 449, in thread_fn
    exporter = BitBucketExport(owner, credentials, copy.deepcopy(self.__settings), lambda cmd, message, i=i, q=message_queue:message_queue.put((i,cmd,message)), subset=subset[i])
  File "c:\users\rpanderson\appdata\local\continuum\anaconda3\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 1480, in __init__
    with open(options['github_URL_rewrite_file_path'], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Perhaps this is related to the fact that the project settings (below) report "These repositories are already on GitHub" even though I selected "I need to create new repositories on GitHub for all previously selected BitBucket repositories" during the Github import settings prompts of the CLI.

```
Project settings:
    Name: bitbucket-hg-exporter-test
    Path: C:\Users\rpanderson\bitbucket-hg-exporter-test
    BitBucket username: rpanderson
    Additional BitBucket accounts:
        None
    Repositories to export:
        rpanderson/********
        rpanderson/********
        rpanderson/********
    Backup forks: False
    Import to GitHub: True
        GitHub username: rpanderson
        GitHub owner: rpanderson
        File containing mapping between BitBucket and GitHub users: C:\Users\rpanderson\bb_gh_user_mapping.json
        Import issues to GitHub issue tracker: False
        Publish BitBucket backup on GitHub pages: False
        Rewrite custom set of URLs in issues/comments/etc: True
            Path containing URL rewrites:
        Import BitBucket forks to GitHub: True
        These repositories are already on GitHub (including imports initiated by this script in previous runs:)
```

**Comment by philipstarkey** [comment]
That's because you answered "y" to the question "Rewrite custom set of URLs in issues/comments/etc". I've changed the default to False so that you have to actively say "y" rather than just hitting enter.

BTW, if you don't have issues/PRs/comments to back up the only benefit you get from using this program is that it will back up and migrate your forks too. I'd you don't have forks, you might want to consider just using the GitHub source import tool directly from the website.

**Comment by rpanderson** [comment]
> That's because you answered "y" to the question "Rewrite custom set of URLs in issues/comments/etc".

I was never asked this question. 

> you might want to consider just using the GitHub source import tool directly from the website.

Thanks! I'll restrict my use of the tool to projects that I want the PR and issue history for.

**Comment by philipstarkey** [comment]
Ah, I see. The question was hidden behind an if statement when it shouldn't have been. Had you been importing issues or publishing the archive to GitHub pages, you would have seen it. I've made the question always appear (if importing to GitHub) and that combined with the previous fix should solve all permutations of hitting this bug!
