### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by scpeters** [philipstarkey/bitbucket-hg-exporter#47]
Thanks so much for open sourcing this tool! It's been really helpful with migrating over 200 repositories for our non-profit that develops open source software for robotics, making a difficult task much more tractable.

**Comment by philipstarkey** [comment]
You're welcome! Glad I could make the process easier :) Despite not wanting to move to git/GitHub, I'm starting to appreciate the git/GitHub integrations with other tools (like VS Code) that are way better than anything Atlassian ever managed to produce. It's been speeding up my workflow a lot. So it's definitely been worth the effort (for me) to move everything properly to GitHub!

**Comment by scpeters** [comment]
Our company was already split between using GitHub and bitbucket, so this was an opportunity to unify our hosting.

Anyway, thanks again!
