### ISSUE TITLE
Importing issues to todo.sr.ht

### ISSUE THREAD

**Issue by techtonik** [philipstarkey/bitbucket-hg-exporter#49]
Are there any scripts that import downloaded .json into https://todo.sr.ht tracker instances?
https://man.sr.ht/todo.sr.ht/api.md#ticket-resource

**Comment by philipstarkey** [comment]
Not that I'm aware of (but I've never used sourcehut). As this is a project for GitHub, I'm closing this issue.

**Comment by techtonik** [comment]
There is a bash script that does basic JSON to JSON field mapping https://hg.sr.ht/~sircmpwn/invertbucket
